name: instagram_ui_clone
description: monfauzi.com.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  marquee: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/avatars/
    - assets/feeds/
    - assets/icons/
    - assets/search/
